### ISSUE TITLE
How to setup

### ISSUE THREAD

**Issue by SPNDK** [iver56/homey-ismartgate#8]
Hi, I have installed the app on my Homey and configured it with UDI and Username, but I can't add or see my iSmartgate?

**Comment by iver56** [comment]
It only supports flows for now, not add device with cards and all that. Related issue: https://github.com/iver56/homey-ismartgate/issues/4

The supported flows are "And" and "Then". Note that "When" is not supported at the moment.

**Comment by iver56** [comment]
@SPNDK Did it help?

**Comment by SPNDK** [comment]
Yes, sorry I didn't reply. I was just wondering why I couldn't add the
device :-)

Den tir. 31. maj 2022 kl. 08.44 skrev Iver Jordal ***@***.***
